CREATE TABLE CAT (
	CAT_VARIETY VARCHAR2(100) NOT NULL, /* 종류 */
	CAT_WEIGHT VARCHAR2(20) NOT NULL, /* 평균체중 */
	CAT_FURCOLOR VARCHAR2(100) NOT NULL, /* 모색 */
	CAT_FURTYPE VARCHAR2(30) NOT NULL, /* 모종 */
	CAT_SRC VARCHAR2(300), /* 이미지경로 */
	CAT_CHARACTER VARCHAR2(3000) NOT NULL /* 특징 */
);

ALTER TABLE CAT
	ADD
		CONSTRAINT PK_CAT
		PRIMARY KEY (
			CAT_VARIETY
		);
select * from CAT;