CREATE TABLE DOG (
	DOG_VARIETY VARCHAR2(100) NOT NULL, /* 종류 */
	DOG_WEIGHT VARCHAR2(20) NOT NULL, /* 평균체중 */
	DOG_FURCOLOR VARCHAR2(100) NOT NULL, /* 모색 */
	DOG_FURTYPE VARCHAR2(30) NOT NULL, /* 모종 */
	DOG_SRC VARCHAR2(300) NOT NULL,/* 이미지경로 */
	DOG_CHARACTER VARCHAR2(3000) NOT NULL /* 특징 */
);
ALTER TABLE DOG
	ADD
		CONSTRAINT PK_DOG
		PRIMARY KEY (
			DOG_VARIETY
		);
        
select * from dog;
